# Generated by scripts/brew-formula.sh on release. Do not edit by hand.
class Refigure < Formula
  desc "Export a Refigure project to images"
  homepage "https://github.com/oduvan/refigure-cli"
  version "0.1.7"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/oduvan/refigure-cli/releases/download/v0.1.7/refigure_v0.1.7_darwin_arm64.tar.gz"
      sha256 "3b19fe218034462f77303592d4a44e2064c32390c73dad69a1da5658c76e8687"
    end
    on_intel do
      url "https://github.com/oduvan/refigure-cli/releases/download/v0.1.7/refigure_v0.1.7_darwin_amd64.tar.gz"
      sha256 "e5748bb567918425732f4400093fd334bd64d66f6e88e52da8fcb58ed528015c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/oduvan/refigure-cli/releases/download/v0.1.7/refigure_v0.1.7_linux_arm64.tar.gz"
      sha256 "e8668f27090a5c04aebc0723f2efa57bed84d4dc44baac3d7ad948d533231851"
    end
    on_intel do
      url "https://github.com/oduvan/refigure-cli/releases/download/v0.1.7/refigure_v0.1.7_linux_amd64.tar.gz"
      sha256 "8e31c7563a70e9f3a0fb81014d82bea6fc69ea9a44589aa2a8f77ecbe9bc8783"
    end
  end

  def install
    bin.install "refigure"
  end

  test do
    assert_match "0.1.7", shell_output("#{bin}/refigure version")
    assert_match "refigure.yaml", shell_output("#{bin}/refigure schema")
  end
end
