# Generated by scripts/brew-formula.sh on release. Do not edit by hand.
class Refigure < Formula
  desc "Export a Refigure project to images"
  homepage "https://github.com/oduvan/refigure-cli"
  version "0.1.6"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/oduvan/refigure-cli/releases/download/v0.1.6/refigure_v0.1.6_darwin_arm64.tar.gz"
      sha256 "c032ec36315898a0aa6bc53dec410cf8395dc95ebc365d7fa9385dccdad38ca4"
    end
    on_intel do
      url "https://github.com/oduvan/refigure-cli/releases/download/v0.1.6/refigure_v0.1.6_darwin_amd64.tar.gz"
      sha256 "b7b0093a33969e0c5af9a3da6d7cf65e9d57d8cf434b314f2c8a226995db13a9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/oduvan/refigure-cli/releases/download/v0.1.6/refigure_v0.1.6_linux_arm64.tar.gz"
      sha256 "68d5b14d425eeb5fd8be9faa643a2bde4c591f5a9c55e8ad5495f14de3abc377"
    end
    on_intel do
      url "https://github.com/oduvan/refigure-cli/releases/download/v0.1.6/refigure_v0.1.6_linux_amd64.tar.gz"
      sha256 "5ead0c0ecb8c5a4a9714433d94df4c00bc57c8625be563568ff3f96454747477"
    end
  end

  def install
    bin.install "refigure"
  end

  test do
    assert_match "0.1.6", shell_output("#{bin}/refigure version")
    assert_match "refigure.yaml", shell_output("#{bin}/refigure schema")
  end
end
