#!/usr/bin/env bash
#
# Writes Formula/refigure.rb for a released version.
#
# The formula installs the published binary rather than building from source:
# there is nothing to compile, and it keeps `brew install` to one download.
#
# Usage: scripts/brew-formula.sh <version> <path to checksums.txt>

set -euo pipefail

version="${1:?usage: brew-formula.sh <version> <checksums.txt>}"
checksums="${2:?usage: brew-formula.sh <version> <checksums.txt>}"

root="$(cd "$(dirname "$0")/.." && pwd)"
base="https://github.com/oduvan/refigure-cli/releases/download/$version"

sha() {
  local asset="$1"
  local line
  line="$(grep " $asset\$" "$checksums" || true)"
  [ -n "$line" ] || { echo "no checksum for $asset" >&2; exit 1; }
  echo "${line%% *}"
}

mkdir -p "$root/Formula"
cat > "$root/Formula/refigure.rb" <<RUBY
# Generated by scripts/brew-formula.sh on release. Do not edit by hand.
class Refigure < Formula
  desc "Export a Refigure project to images"
  homepage "https://github.com/oduvan/refigure-cli"
  version "${version#v}"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/refigure_${version}_darwin_arm64.tar.gz"
      sha256 "$(sha "refigure_${version}_darwin_arm64.tar.gz")"
    end
    on_intel do
      url "$base/refigure_${version}_darwin_amd64.tar.gz"
      sha256 "$(sha "refigure_${version}_darwin_amd64.tar.gz")"
    end
  end

  on_linux do
    on_arm do
      url "$base/refigure_${version}_linux_arm64.tar.gz"
      sha256 "$(sha "refigure_${version}_linux_arm64.tar.gz")"
    end
    on_intel do
      url "$base/refigure_${version}_linux_amd64.tar.gz"
      sha256 "$(sha "refigure_${version}_linux_amd64.tar.gz")"
    end
  end

  def install
    bin.install "refigure"
  end

  test do
    assert_match "${version#v}", shell_output("#{bin}/refigure version")
    assert_match "refigure.yaml", shell_output("#{bin}/refigure schema")
  end
end
RUBY

echo "wrote Formula/refigure.rb for $version"
